- name: Install Elastic Dependencies (Ubuntu)
  apt:
    name:
      - openjdk-11-jdk
      - apt-transport-https
      - curl
      - gpgv
      - gpgsm
      - gnupg-l10n
      - gnupg
      - dirmngr
    state: latest

- name: Get PGP Key (Ubuntu)
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch sources list (Ubuntu)
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Elasticsearch (Ubuntu)
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes

- name: Configure Elasticsearch cluster name (Ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "cluster.name: demo-elk"
    state: present

- name: Configure Elasticsearch descriptive name (Ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "node.name: elk-1"
    state: present

- name: Configure Elasticsearch Adding network.host (Ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: 0.0.0.0"
    state: present

- name: Configure Elasticsearch Adding http.port (Ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "http.port: 9200"
    state: present

- name: Configure Elasticsearch Adding discovery.type (Ubuntu)
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: "discovery.type: single-node"
    state: present

- name: Creating empty file for startup-timeout.conf 1 of 2 (Ubuntu)
  file:
    path: "/etc/systemd/system/elasticsearch.service.d"
    state: directory

- name: Creating an empty file for startup-timeout.conf 2 of 2 (Ubuntu)
  file:
    path: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    state: touch

- name: Prevent systemd service start operation from timing out (Ubuntu)
  copy:
    dest: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
    content: |
      [Service]
      TimeoutStartSec=3min
- name: Run daemon-reload for elasticsearch (Ubuntu)
  systemd: daemon_reload=yes

- name: Enable service Elasticsearch and ensure it is not masked (Ubuntu)
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running (Ubuntu)
  systemd: state=started name=elasticsearch

- name: Install Logstash (Ubuntu)
  apt:
    name: logstash
    state: latest
    update_cache: yes

- name: Run daemon-reload for logstash (Ubuntu)
  systemd: daemon_reload=yes

- name: Enable service logstash (Ubuntu)
  systemd:
    name: logstash
    enabled: yes

- name: ensure logstash is running (Ubuntu)
  systemd: state=started name=logstash

- name: Install Kibana (Ubuntu)
  apt:
    name: kibana
    state: latest
    update_cache: yes

- name: Configure Kibana Add server.port (Ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: "server.port: 5601"
    state: present

- name: Configure Kibana Add server.host (Ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.host: "0.0.0.0"'
    state: present

- name: Configure Kibana Add server.name (Ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'server.name: "demo-kibana"'
    state: present

- name: Configure Kibana Add elasticsearch.hosts (Ubuntu)
  lineinfile:
    dest: /etc/kibana/kibana.yml
    line: 'elasticsearch.hosts: ["http://0.0.0.0:9200"]'
    state: present

- name: Run daemon-reload for kibana (Ubuntu)
  systemd: daemon_reload=yes

- name: Enable service Kibana (Ubuntu)
  systemd:
    name: kibana
    enabled: yes

- name: Start Elasticsearch service
  shell: systemctl start elasticsearch

- name: Start Kibana
  shell: systemctl start kibana
